on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch_depth: 0
          fetch_tags: true
      - name: Get Pokemon name
        uses: ./
          # uses: philschmid/blog-custom-github-action@master
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
